version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8080/api
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api
    ports:
      - "3000:80"
    container_name: frontend-app

  backend:
    build:
      context: ./backend/spp-kotlin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend-app
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/spp

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: