jwt.secret=${JWT_SECRET:K8L1JyRkWS9zQcy8n9p2K4g1Hn7aVf3XqYt6m8b2}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
spring.application.name=spp-kotlin
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/spp}
